# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e91c282f5ecf71a10016bd85fe2ed21390567dd0de91db8ae1caae37e1e4bccef5b593e31ea3e0688e7d79e672c21aa38e135a5287bc02df7fffbe2ba3e8c709

test:
  secret_key_base: bddb856f188fb3eb9a4737dbcb289fa42d18cf09d7f12abb88d67b229ed5f5f5f5b330ef003bb5f4e92a1ed2fd7e63382a742fddcc5ac6319aae7cb645174b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
